
# Performance
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true
